from sqlalchemy import Table, Column, Integer, Float, String, MetaData, ForeignKey

metadata = MetaData()
species = Table('species', metadata,
                Column('tax_id', Integer, primary_key=True),
                Column('name', String))

pairs =   Table('pairs', metadata,
                Column('pair_id', Integer, primary_key=True),
                Column('tax_id', Integer, ForeignKey('species.tax_id'), nullable=False),
                Column('rev', Integer, nullable=False),
                Column('id_a', String, nullable=False),
                Column('id_b', String, nullable=False),
                Column('uniprot_ac_a', String, nullable=False),
                Column('uniprot_ac_b', String, nullable=False),
                Column('tpl', String),
                Column('query_type', String),
                Column('template_type', String),
                Column('score_model_z', Float),
                Column('score_model_minus_avg', Float),
                Column('score3', Float),
                Column('score4', Float),
                Column('score5', Float),
                Column('score6', Float),
                Column('identical_a', Integer),
                Column('identical_b', Integer),
                Column('positive_a', Integer),
                Column('positive_b', Integer),
                Column('aln_len_a', Integer),
                Column('aln_len_b', Integer),
                Column('bs_len_a', Integer),
                Column('bs_len_b', Integer),
                Column('bs_covered_a', Integer),
                Column('bs_covered_b', Integer),
                Column('bs_aligned_a', Integer),
                Column('bs_aligned_b', Integer),
                Column('bs_identical_a', Integer),
                Column('bs_identical_b', Integer),
                Column('bs_positive_a', Integer),
                Column('bs_positive_b', Integer),
                Column('bs_contacts_a', Integer),
                Column('bs_contacts_b', Integer),
                Column('bs_blosum_a', Float),
                Column('bs_blosum_b', Float),
                Column('bs_score1_a', Float),
                Column('bs_score1_b', Float),
                Column('site_a', String),
                Column('site_b', String))

proteins = Table('proteins', metadata,
                 Column('uniprot_ac', String, primary_key=True),
                 Column('uniprot_accessions', String),
                 Column('uniprot_id', String),
                 Column('tax_id', Integer, ForeignKey('species.tax_id'), nullable=False),
                 Column('name', String),
                 Column('sequence', String),
                 Column('seqlen', Integer))

idmapping = Table('idmapping', metadata,
                  Column('uniprot_ac', String, primary_key=True, nullable=True),
                  Column('uniprot_id', String),
                  Column('gene_id', Integer),
                  Column('gi', Integer),
                  Column('refseq', String),
                  Column('pdb', String),
                  Column('go', String),
                  Column('ensembl', String))
